# Generated by Django 4.1.7 on 2023-07-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etf',
            fields=[
                ('tickers', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('etf_name', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=20)),
                ('return_3m', models.FloatField()),
            ],
            options={
                'db_table': 'etf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KrPrice',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volumne', models.FloatField(blank=True, null=True)),
                ('tickers', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'kr_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KrSector',
            fields=[
                ('tickers', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cmp_name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kr_sector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KrTicker',
            fields=[
                ('tickers', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cmp_name', models.CharField(max_length=100)),
                ('mkt', models.CharField(max_length=100)),
                ('mkt_cap', models.IntegerField()),
                ('eps', models.FloatField(blank=True, null=True)),
                ('before_eps', models.FloatField(blank=True, null=True)),
                ('bps', models.FloatField(blank=True, null=True)),
                ('dividend', models.FloatField(blank=True, null=True)),
                ('class_field', models.CharField(db_column='class', max_length=20)),
            ],
            options={
                'db_table': 'kr_ticker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('parent_etf_ticker', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tickers', models.CharField(max_length=20)),
                ('cmp_name', models.CharField(max_length=100)),
                ('mkt_cap', models.IntegerField()),
                ('mkt', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pdf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('tickers', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('shares', models.BigIntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThemeInfo',
            fields=[
                ('theme_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('theme_title', models.CharField(blank=True, max_length=100, null=True)),
                ('theme_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'theme_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThemePdfs',
            fields=[
                ('stk_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('theme_title', models.CharField(max_length=100)),
                ('stk_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'theme_pdfs',
                'managed': False,
            },
        ),
    ]
