# Generated by Django 4.1.7 on 2023-07-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinNews',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.TextField(blank=True, null=True)),
                ('thumb_url', models.TextField(blank=True, null=True)),
                ('view', models.IntegerField(blank=True, null=True)),
                ('src', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coin_news',
                'managed': False,
            },
        ),
    ]
