# Generated by Django 4.1.7 on 2023-07-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_coinnews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinnews',
            options={'managed': True},
        ),
    ]
