# Generated by Django 4.1.7 on 2023-07-31 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_alter_coinnews_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinnews',
            options={},
        ),
        migrations.AlterModelTable(
            name='coinnews',
            table=None,
        ),
    ]
