# Generated by Django 4.1.7 on 2023-07-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_alter_coinnews_options_alter_coinnews_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinnews',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
