# Generated by Django 4.1.7 on 2023-08-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_coinnews_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinnews',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
