# Generated by Django 4.1.7 on 2023-08-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0010_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='subscribers',
            table='subscribers',
        ),
    ]
